version: '3'
services:
  web:
    build: .
    ports:
      - "5000:5000"
    env_file: web-example.env
    depends_on:
      - db
    volumes:
      - ./:/opt/webapp
    command: python runserver.py
  db:
    image: postgres:latest
    env_file: db.env
    volumes:
      - pgdata:/var/lib/postgresql/data
  redis:
    image: redis:alpine
volumes:
  pgdata: